version: '3'

volumes:
  database:
    driver: local

services:
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: super
      MYSQL_PASSWORD: super
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:      
      - "8088:8080"
